# Generated by Django 4.2.11 on 2024-03-31 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                ("primary_color", models.CharField(default="#4d6fa9", max_length=255)),
                (
                    "secondary_color",
                    models.CharField(default="#253447", max_length=255),
                ),
                ("accent_color", models.CharField(default="#76a8d4", max_length=255)),
                ("success_color", models.CharField(default="#00a896", max_length=255)),
                ("info_color", models.CharField(default="#118ab2", max_length=255)),
                ("warning_color", models.CharField(default="#ff8c00", max_length=255)),
                ("danger_color", models.CharField(default="#e71d36", max_length=255)),
                (
                    "background_color",
                    models.CharField(default="#f4f7fc", max_length=255),
                ),
                ("text_color", models.CharField(default="#333333", max_length=255)),
                (
                    "primary_hover_color",
                    models.CharField(default="#3c5984", max_length=255),
                ),
                (
                    "secondary_hover_color",
                    models.CharField(default="#1e293d", max_length=255),
                ),
                (
                    "accent_hover_color",
                    models.CharField(default="#648fb8", max_length=255),
                ),
                (
                    "success_hover_color",
                    models.CharField(default="#009980", max_length=255),
                ),
                (
                    "info_hover_color",
                    models.CharField(default="#0e708b", max_length=255),
                ),
                (
                    "warning_hover_color",
                    models.CharField(default="#e67600", max_length=255),
                ),
                (
                    "danger_hover_color",
                    models.CharField(default="#c61a2b", max_length=255),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.theme",
            ),
        ),
    ]
