# Generated by Django 4.2.11 on 2024-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storymmode_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("meta_description", models.TextField()),
            ],
        ),
    ]
