# Generated by Django 4.2.11 on 2024-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storymmode_api", "0002_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAiUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("related_user_ids", models.TextField(default="")),
                ("related_conversation_ids", models.TextField(default="")),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="tags",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="location",
            name="tags",
            field=models.TextField(default=""),
        ),
    ]
