# Generated by Django 4.2.11 on 2024-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storymmode_api", "0005_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiuser",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="openaiuser",
            name="inventory",
            field=models.TextField(blank=True, default=""),
        ),
    ]
